### ISSUE TITLE
AttributeError: 'osdb' object has no attribute 'use'

### ISSUE THREAD

**Issue by yuexiajiayan** [OpenSIPS/opensips-cli#22] opened 2019-06-25 07:08 UTC
SQLAlchemy version:  1.3.3
Please provide us the URL of the database: mysql://root:lilin$@127.0.0.1
Traceback (most recent call last):
  File "/usr/local/bin/opensips-cli", line 4, in <module>
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1438, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 59, in execfile
    exec(compile(open(fn).read(), fn, 'exec'), globs, locs)
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/EGG-INFO/scripts/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/EGG-INFO/scripts/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/cli.py", line 225, in cmdloop
    ret = self.run_command(self.command[0], command, params)
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/cli.py", line 331, in run_command
    return mod[0].__invoke__(cmd, params)
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/module.py", line 36, in __invoke__
    return f(params)
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/modules/user.py", line 103, in do_add
    db = self.user_db_connect()
  File "/usr/local/lib/python3.4/dist-packages/opensipscli-0.1-py3.4.egg/opensipscli/modules/user.py", line 55, in user_db_connect
    db.use()
AttributeError: 'osdb' object has no attribute 'use'

**Comment by liviuchircu** [comment] 2019-06-25 07:55
Duplicate of #16. Closing.

**Closed by liviuchircu** 2019-06-25 07:55 UTC

**Comment by liviuchircu** [comment] 2019-06-25 16:59
@yuexiajiayan please pull latest code and try again.  Cheers!
