### ISSUE TITLE
Add ability to create user

### ISSUE THREAD

**Issue by sdwru** [OpenSIPS/opensips-cli#39] opened 2020-01-17 15:25 UTC
`/usr/sbin/opensipsdbctl create` asked for the root password and then created `opensips` user with all the proper DB permissions.  It appears `opensips-cli -x database create` does not duplicate that behavior, requiring me to create the `opensips` DB user and permissions manually.  Using root user is not a good idea so it would be nice if the previous behavior were duplicated.

**Comment by liviuchircu** [comment] 2020-03-06 09:32
Duplicate of #20, closing here.  Coming up with a "behind-the-curtains" solution for this problem is now on the top my TODO list.

**Closed by liviuchircu** 2020-03-06 09:32 UTC
