### ISSUE TITLE
database creation fails

### ISSUE THREAD

**Issue by lukasbraach** [OpenSIPS/opensips-cli#13] opened 2019-06-06 20:31 UTC
When I try to create a database with opensips-cli, the program just crashes:
```
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError) unsupported operand type(s) for %: 'bytes' and 'tuple'
[SQL: SHOW VARIABLES LIKE 'sql_mode']
(Background on this error at: http://sqlalche.me/e/f405)
```
OpenSIPS 3.0 is freshly installed from source in a custom location. Honestly I am just trying this project as I can neither find `opensipsdbctl` nor `opensipsctl` in my installation's location. 

[Full log of opensips-cli here](https://github.com/OpenSIPS/opensips-cli/files/3263340/opensips-cli.database.create.error.txt)

**Comment by acheraime** [comment] 2019-06-13 02:57
PostgresQL database creation fail as well.
sqlalchemy.exc.InternalError: (psycopg2.InternalError) CREATE DATABASE cannot run inside a transaction block

[SQL: CREATE DATABASE opensips]
(Background on this error at: http://sqlalche.me/e/2j85)
[Traceback: opensips-cli-postgres-error.txt](https://github.com/OpenSIPS/opensips-cli/files/3283926/opensips-cli-postgres-error.txt)

**Comment by lukasbraach** [comment] 2019-06-13 13:53
A little update: While `opensips-cli` still does not work on my Raspberry Pi, it works flawlessly on my x86-64 Debian installation. I thought Python was running equally on all platforms :-?

**Comment by razvancrainea** [comment] 2019-06-13 15:22
@lukasbraach aparently the problem is that MySQLdb is no longer supported, and you should use a different mysqldb engine. For example, can you try to install `python3-pymysql` and try again?
@acheraime I will look into the postgres issue too and get back to you.

**Comment by razvancrainea** [comment] 2019-06-14 15:19
@acheraime I tried to replicate this, but I couldn't.
Can you change [this](https://github.com/OpenSIPS/opensips-cli/blob/master/opensipscli/db.py#L66) line with something like:
```
            self.__engine = sqlalchemy.create_engine(db_url, isolation_level="AUTOCOMMIT")
```
Then install `opensips-cli` again and test?

Best regards,
Răzvan

**Comment by acheraime** [comment] 2019-06-14 16:03
Yeah!

I did that already. I was able to run the database create command with no issues.
Now my problem is when I try to add a table like it return a database not exist error.

I’ll continue to dig further to see what the problem is.

**Comment by vma** [comment] 2019-06-15 21:44
I have a similar issue, typing just database on the cli make it crash:

```
(opensips-cli): database                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                            
  File "/usr/lib/python3.5/cmd.py", line 214, in onecmd                                                                                                                                                                               
    func = getattr(self, 'do_' + cmd)                                                                                                                                                                                               
AttributeError: 'OpenSIPSCLIShell' object has no attribute 'do_database'                                                                                                                                                            
                                                                                                                                                                                                                                     
During handling of the above exception, another exception occurred:                                                                                                                                                                   
                                                                                                                                                                                                                                      
Traceback (most recent call last):                                                                                                                                                                                                    
  File "/usr/local/bin/opensips-cli", line 4, in <module>                                                                                                                                                                             
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')                                                                                                                                                          
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 739, in run_script                                                                                                                                       
    self.require(requires)[0].run_script(script_name, ns)                                                                                                                                                                        
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1494, in run_script                                                                                                                                                   
    exec(code, namespace, namespace)                                                                                                                                                                                                          
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/EGG-INFO/scripts/opensips-cli", line 9, in <module>                                                                                                          
    run_console()                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/EGG-INFO/scripts/opensips-cli", line 6, in run_console                                                                                                     
    main.main()                                                                                                                                                                                                                     
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/main.py", line 78, in main                                                                                                                     
    sys.exit(shell.cmdloop())                                                                                                                                                                                                         
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 232, in cmdloop                                                                                                                    
    super(OpenSIPSCLIShell, self).cmdloop(intro='')                                                                                                                                                                                   
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop                                                                                                                                                                              
    stop = self.onecmd(line)                                                                                                                                                                                                      
  File "/usr/lib/python3.5/cmd.py", line 216, in onecmd                                                                                                                                                                          
    return self.default(line)                                                                                                                                                                                                                 
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 342, in default                                                                                                                            
    self.run_command(module, cmd, params)                                                                                                                                                                                                     
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 330, in run_command                                                                                                                
    logger.debug("running command '%s' with %i arguments: %s'", cmd, len(params), params)                                                                                                                                           
TypeError: object of type 'NoneType' has no len()                                                                              
```

I miss opensipsctl.

**Comment by liviuchircu** [comment] 2019-06-16 05:42
Thanks for the catch, @vma!  Just fixed this in cfe24b992 - the error was introduced along with a recent code merge (support for Postgres roles).  As a developer, I don't miss opensipsctl at all, and I'm thrilled that we are now hacking on a console/project that people (including ourselves) actually take pleasure in contributing to :)

**Comment by tangshiixang** [comment] 2019-06-18 07:20
When I try to create a database with opensips-cli,  the program throw same exception raised by lukasbraach (https://github.com/OpenSIPS/opensips-cli/issues/13#issue-453225177). I have install python3-pymysql instead of mysqlclient ,but there's nothing better.

**Comment by liviuchircu** [comment] 2019-06-18 07:32
@tangshiixang what environment / python3 / packages are you using?  (`pip freeze`, `python3 -V`, `dpkg -l | grep -i python3`).  Being able to reproduce this issue would help a lot.

**Comment by tangshiixang** [comment] 2019-06-18 08:02
pip3 freeze:
Magic-file-extensions==0.2
PyMySQL==0.9.3
SQLAlchemy==1.3.3
SQLAlchemy-Utils==0.34.0
chardet==2.3.0
colorama==0.3.2
devscripts==2.15.3-deb8u1
html5lib==0.999
mysqlclient==1.4.2.post1
opensipscli==0.1
python-apt==0.9.3.12
python-debian==0.1.27
requests==2.4.3
six==1.12.0
urllib3==1.9.1
wheel==0.24.0

python3 -V:
Python 3.4.2

dpkg -l | grep -i python3
ii  libpython3-dev:amd64                3.4.2-2                          amd64        header files and a static library for Python (default)
ii  libpython3-stdlib:amd64             3.4.2-2                          amd64        interactive high-level object-oriented language (default python3 version)
ii  libpython3.4:amd64                  3.4.2-1+deb8u2                   amd64        Shared Python runtime library (version 3.4)
ii  libpython3.4-dev:amd64              3.4.2-1+deb8u2                   amd64        Header files and a static library for Python (v3.4)
ii  libpython3.4-minimal:amd64          3.4.2-1+deb8u2                   amd64        Minimal subset of the Python language (version 3.4)
ii  libpython3.4-stdlib:amd64           3.4.2-1+deb8u2                   amd64        Interactive high-level object-oriented language (standard library, version 3.4)
ii  python3                             3.4.2-2                          amd64        interactive high-level object-oriented language (default python3 version)
ii  python3-apt                         0.9.3.12                         amd64        Python 3 interface to libapt-pkg
ii  python3-chardet                     2.3.0-1                          all          universal character encoding detector for Python3
ii  python3-colorama                    0.3.2-1                          all          Cross-platform colored terminal text in Python - Python 3.x
ii  python3-debian                      0.1.27                           all          Python 3 modules to work with Debian-related data formats
ii  python3-dev                         3.4.2-2                          amd64        header files and a static library for Python (default)
ii  python3-distlib                     0.1.9-1                          all          low-level components of python distutils2/packaging
ii  python3-html5lib                    0.999-3                          all          HTML parser/tokenizer based on the WHATWG HTML5 specification (Python 3)
ii  python3-magic                       1:5.22+15-2+deb8u5               all          File type determination library using "magic" numbers (Python 3 bindings)
ii  python3-minimal                     3.4.2-2                          amd64        minimal subset of the Python language (default python3 version)
ii  python3-pip                         1.5.6-5                          all          alternative Python package installer - Python 3 version of the package
ii  python3-pkg-resources               5.5.1-1                          all          Package Discovery and Resource Access using pkg_resources
ii  python3-requests                    2.4.3-6                          all          elegant and simple HTTP library for Python3, built for human beings
ii  python3-setuptools                  5.5.1-1                          all          Python3 Distutils Enhancements
ii  python3-six                         1.8.0-1                          all          Python 2 and 3 compatibility library (Python 3 interface)
ii  python3-urllib3                     1.9.1-3                          all          HTTP library with thread-safe connection pooling for Python3
ii  python3-wheel                       0.24.0-1                         all          built-package format for Python
ii  python3.4                           3.4.2-1+deb8u2                   amd64        Interactive high-level object-oriented language (version 3.4)
ii  python3.4-dev                       3.4.2-1+deb8u2                   amd64        Header files and a static library for Python (v3.4)
ii  python3.4-minimal                   3.4.2-1+deb8u2                   amd64        Minimal subset of the Python language (version 3.4)

My os  version is debian 8.

**Comment by vma** [comment] 2019-06-18 09:39
Hi @liviuchircu,
Thanks for the fix and please accept my apologies for my last sentence about opensipsctl. It was inappropriate and was made in the heat of the moment.
Also thank for the great work!

**Comment by liviuchircu** [comment] 2019-06-18 11:07
@tangshiixang thanks for the detailed info, managed to reproduce instantly.  A fix is on its way!

**Comment by liviuchircu** [comment] 2019-06-18 12:22
The problem seems to be directly related to Python3.4, which does not allow bytes to be formatted:

```>>> b"my_bytes" % tuple()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'
```

The above code (and hence the `opensips-cli`) will start working once we switch to Python3.5+.  Trying to find an easy way to install Python3.5+ on older systems now.  Also, I will dig a bit into the SQLAlchemy docs and find out what exact Python3 the whole package requires, if this is specified in the first place.

**Comment by bhagatsameer** [comment] 2019-06-18 12:55
I am also having the same issue when trying to create Database in PostgreSQL. I am trying this on Debian 9 with Python 3.5.3.

Is the issue due to the version of Python? Should I use a lower version of Python? If yes then what version, please?

==================

Traceback (most recent call last):
  File "/usr/lib/python3.5/cmd.py", line 214, in onecmd
    func = getattr(self, 'do_' + cmd)
AttributeError: 'OpenSIPSCLIShell' object has no attribute 'do_database'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.SyntaxError: syntax error at or near "USE"
LINE 1: USE test
        ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/opensips-cli", line 4, in <module>
    __import__('pkg_resources').run_script('opensipscli==0.1', 'opensips-cli')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/EGG-INFO/scripts/opensips-cli", line 9, in <module>
    run_console()
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/EGG-INFO/scripts/opensips-cli", line 6, in run_console
    main.main()
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/main.py", line 78, in main
    sys.exit(shell.cmdloop())
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 232, in cmdloop
    super(OpenSIPSCLIShell, self).cmdloop(intro='')
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.5/cmd.py", line 216, in onecmd
    return self.default(line)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 342, in default
    self.run_command(module, cmd, params)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/cli.py", line 331, in run_command
    return mod[0].__invoke__(cmd, params)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/module.py", line 36, in __invoke__
    return f(params)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/modules/database.py", line 376, in do_create
    if self.create_tables(db_name, db_url=db_url) < 0:
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/modules/database.py", line 462, in create_tables
    db.connect(db_name)
  File "/usr/local/lib/python3.5/dist-packages/opensipscli-0.1-py3.5.egg/opensipscli/db.py", line 174, in connect
    self.__conn.execute("USE {}".format(self.db_name))
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 982, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1155, in _execute_text
    parameters,
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.5/dist-packages/SQLAlchemy-1.3.3-py3.5-linux-x86_64.egg/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.SyntaxError) syntax error at or near "USE"
LINE 1: USE test
        ^

[SQL: USE test]
(Background on this error at: http://sqlalche.me/e/f405)

==================

**Comment by liviuchircu** [comment] 2019-06-18 13:37
@tangshiixang and @lukasbraach : the cli is now _more compatible_ Python3.4 systems.  Please let me know if you run into any other errors.

**Comment by liviuchircu** [comment] 2019-06-18 13:38
@bhagatsameer : what is the cli command that you are running?

**Comment by bhagatsameer** [comment] 2019-06-18 13:39
I am running database create

**Comment by liviuchircu** [comment] 2019-06-18 13:40
@tangshiixang @lukasbraach : My answer was a bit rushed.  The solution involves downgrading to a pre `1.4.0` version of `mysqlclient`, which is compatible with Python3.4.  Re-running `python3 setup.py install clean` should be enough.

**Comment by bhagatsameer** [comment] 2019-06-18 13:46
@liviuchircu I am trying to create DB on PGSQL

**Comment by bhagatsameer** [comment] 2019-06-18 14:09
I was able to make it work on Debian 8 with Python 3.4. Additional Python modules need to be installed for the script to run for PGSQL.

apt-get install libpq-dev

pip3 install psycopg2  psycopg2-binary

Thanks for your help @liviuchircu

**Comment by liviuchircu** [comment] 2019-06-18 14:10
@bhagatsameer , this is how I got it working with PGSQL.  This is a recently merged support, so it still needs a bit of testing / fiddling around with before it's as easy to use as MySQL.

```
(opensips-cli): database create_db opensips
Please provide the URL to connect to as template: postgres://liviu:liviuspsqlpassword@localhost:5432/opensips_2_2
INFO: Database 'opensips' for dialect 'postgres' created
Please provide the associated role name to access the database (Default value is opensips): 
INFO: granted options 'ALL PRIVILEGES' to role 'opensips' on database 'opensips'
(opensips-cli): 
(opensips-cli): database create_module standard
Please provide the URL to connect to the database: postgres://liviu:liviuspsqlpassword@localhost:5432/opensips
Please provide the path to the OpenSIPS DB scripts: /home/liviu/src/opensips/scripts
INFO: database tables for module '['standard']' has been successfully created.
(opensips-cli): 
(opensips-cli): database create_module dialog
Please provide the URL to connect to the database: postgres://liviu:liviuspsqlpassword@localhost:5432/opensips
INFO: database tables for module '['dialog']' has been successfully created.
```

**Comment by tangshiixang** [comment] 2019-06-19 01:15
@liviuchircu , thank you for your timely efforts, the program can work now. Yet I met with another little doubt. I was asked to enter mysql uri when I create database with opensips-cli, but I already configured mysql uri in the configuration file and I also used true instance in configuration file. Is this a normal phenomenon?

**Comment by liviuchircu** [comment] 2019-06-19 11:06
@tangshiixang maybe this is a bit undocumented, but if you specify:

```
template_url: mysql://root:liviusmysqlpassword@localhost
```

under the `[default]` section of `~/.opensips-cli.cfg`, the CLI will no longer ask for a DB URL.  If you still get DB URL inquiries after setting this, please open a separate issue, so we can take care of it.   Thanks!

**Comment by liviuchircu** [comment] 2019-06-19 11:37
So the only remaining issue here is yours, @acheraime, correct?

**Comment by liviuchircu** [comment] 2019-06-27 12:52
The last-standing issue here was moved to #23.  Closing.

**Closed by liviuchircu** 2019-06-27 12:52 UTC
Labels: bug
